server:
  port: 8083

management:
  port: 8003

spring:
  application:
    name: ProductService

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4500